"""Added objects in class Message

Revision ID: 40d9e788b0f0
Revises: 6153cca1fb2f
Create Date: 2026-08-15 18:54:29.645677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d9e788b0f0'
down_revision: Union[str, Sequence[str], None] = '6153cca1fb2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'created_at')
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###
